### ISSUE TITLE
IllegalStateException: Broadcast already finished

### ISSUE THREAD

**Issue by d4rken** [d4rken/wakelock-revamp#6]
## Error in WakeLock v3

**java.lang.IllegalStateException** in **LockCommandReceiver.kt:66**
Broadcast already finished

[View on Bugsnag](https://app.bugsnag.com/darken-development/wakelock-v3/errors/5b844f2e436ffe0018991697?event_id=5b857b62002dbf29def50000&i=gh&m=ci)

## Stacktrace

    LockCommandReceiver.kt:66 - eu.thedarken.wldonate.main.core.receiver.LockCommandReceiver$releaseAll$2.run

[View full stacktrace](https://app.bugsnag.com/darken-development/wakelock-v3/errors/5b844f2e436ffe0018991697?event_id=5b857b62002dbf29def50000&i=gh&m=ci)

*Created by Matthias Urhahn via Bugsnag*

**Comment by d4rken** [comment]
```
java.lang.IllegalStateException: Broadcast already finished
        at android.content.BroadcastReceiver$PendingResult.sendFinished(BroadcastReceiver.java:410)
        at android.content.BroadcastReceiver$PendingResult.finish(BroadcastReceiver.java:389)
        at eu.thedarken.wldonate.main.core.receiver.LockCommandReceiver$releaseAll$2.run(LockCommandReceiver.kt:66)
        at io.reactivex.internal.operators.completable.CompletableDoFinally$DoFinallyObserver.runFinally(CompletableDoFinally.java:98)
        at io.reactivex.internal.operators.completable.CompletableDoFinally$DoFinallyObserver.onComplete(CompletableDoFinally.java:81)
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onComplete(CompletableSubscribeOn.java:79)
        at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onComplete(CompletablePeek.java:116)
        at io.reactivex.internal.operators.completable.CompletableFromSingle$CompletableFromSingleObserver.onSuccess(CompletableFromSingle.java:51)
        at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:59)
        at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
        at io.reactivex.internal.operators.observable.ObservableElementAtSingle$ElementAtObserver.onNext(ObservableElementAtSingle.java:91)
        at io.reactivex.internal.util.NotificationLite.accept(NotificationLite.java:246)
        at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.test(BehaviorSubject.java:570)
        at io.reactivex.subjects.BehaviorSubject$BehaviorDisposable.emitFirst(BehaviorSubject.java:531)
        at io.reactivex.subjects.BehaviorSubject.subscribeActual(BehaviorSubject.java:239)
        at io.reactivex.Observable.subscribe(Observable.java:12036)
        at io.reactivex.internal.operators.observable.ObservableElementAtSingle.subscribeActual(ObservableElementAtSingle.java:37)
        at io.reactivex.Single.subscribe(Single.java:3313)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3313)
        at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
        at io.reactivex.Single.subscribe(Single.java:3313)
        at io.reactivex.internal.operators.completable.CompletableFromSingle.subscribeActual(CompletableFromSingle.java:29)
        at io.reactivex.Completable.subscribe(Completable.java:1918)
        at io.reactivex.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.Completable.subscribe(Completable.java:1918)
        at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
        at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
        at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
```

**Comment by d4rken** [comment]
This issue has been linked to an error in Bugsnag
[**java.lang.IllegalStateException** in **com.android.launcher2.Launcher**](https://app.bugsnag.com/darken-development/wakelock-v3/errors/5b844c2492d8a200186222e2?event_id=5b8573e7002dbe82ff490000&i=gh&m=li)

**Comment by d4rken** [comment]
It's a race condition against the broadcast receiver itself finishing before we `goAsync()`. So we need to `goAsync()` while still on the main thread instead of on `Schedulers.computation()`.
