### ISSUE TITLE
NPE when launching the billing flow

### ISSUE THREAD

**Issue by d4rken** [d4rken/wakelock-revamp#7]
## Error in WakeLock v3

**java.lang.RuntimeException** in **ActivityThread.java:2211**
Unable to start activity ComponentInfo{eu.thedarken.wldonate/com.android.billingclient.api.ProxyBillingActivity}: java.lang.NullPointerException

[View on Bugsnag](https://app.bugsnag.com/darken-development/wakelock-v3/errors/5b8490e2e747f5001abaeb80?event_id=5b84c968002ddfcba0c90000&i=gh&m=ci)

## Stacktrace

    ActivityThread.java:2211 - android.app.ActivityThread.performLaunchActivity

[View full stacktrace](https://app.bugsnag.com/darken-development/wakelock-v3/errors/5b8490e2e747f5001abaeb80?event_id=5b84c968002ddfcba0c90000&i=gh&m=ci)

*Created by Matthias Urhahn via Bugsnag*

**Comment by d4rken** [comment]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.thedarken.wldonate/com.android.billingclient.api.ProxyBillingActivity}: java.lang.NullPointerException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
        at android.app.ActivityThread.access$600(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5103)
        at java.lang.reflect.Method.invokeNative(Method.java:-2)
        at java.lang.reflect.Method.invoke(Method.java:525)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:-2)
        at dalvik.system.NativeStart.main(NativeStart.java:-2)
Caused by: java.lang.NullPointerException
        at com.android.billingclient.api.ProxyBillingActivity.onCreate(ProxyBillingActivity.java:34)
        at android.app.Activity.performCreate(Activity.java:5133)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
        at android.app.ActivityThread.access$600(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5103)
        at java.lang.reflect.Method.invokeNative(Method.java:-2)
        at java.lang.reflect.Method.invoke(Method.java:525)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:-2)
        at dalvik.system.NativeStart.main(NativeStart.java:-2)
```

**Comment by d4rken** [comment]
Not a bug in our code, fluke/framework issue.

**Comment by d4rken** [comment]
An error linked to this issue has been reopened in Bugsnag
[**java.lang.RuntimeException** in **ActivityThread.java:2211**](https://app.bugsnag.com/darken-development/wakelock-v3/errors/5b8490e2e747f5001abaeb80?event_id=5b8c3a48002dcb4cae620000&i=gh&m=ra)

**Comment by d4rken** [comment]
An error linked to this issue has been reopened in Bugsnag
[**java.lang.RuntimeException** in **com.android.billingclient.api.ProxyBillingActivity**](https://app.bugsnag.com/darken-development/wakelock-v3/errors/5b8490e2e747f5001abaeb80?event_id=5b9032e7002dd4c73fcf0000&i=gh&m=ra)
